-- CreateTable
CREATE TABLE `TempGoogleAuthRole` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `role` ENUM('STABLE', 'RIDER', 'INSTRUCTOR', 'ADMIN') NOT NULL,
    `isApplied` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
