-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('AFFILIATION_REQUEST', 'AFFILIATION_REQUEST_APPROVED', 'AFFILIATION_REQUEST_REJECTED', 'SYSTEM', 'FROM_STABLE', 'SUCCESS', 'INFO', 'VALIDATION') NOT NULL DEFAULT 'AFFILIATION_REQUEST';
